server:
  port : 8080

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jandb
    driver-class-name: org.mariadb.jdbc.Driver
    #username: jandb
    #password: jandb
    username: ENC(AOlqjc7Vu97CirlATUxSDg==)
    password: ENC(qg5r8Eg7+MunDRuXG0nfcg==)
#url: jdbc:mariadb://127.0.0.1:3306/jandb
logging:
  config: classpath:log/logback-spring.xml

encrypt:
  algolithm: PBEWithMD5AndDES
  key-obtention-iterations: 1000
  pool-size: 1
  salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
  string-output-type: base64

springdoc:
  swagger-ui:
    # swagger-ui 접근 경로. default 값은 /swagger-ui.html이다.
    path: /swagger-ui

    # 태그 정렬 순서.
    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha

    # 컨트롤러 정렬 순서.
    # method는 delete - get - patch - post - put 순으로 정렬된다.
    # alpha를 사용해 알파벳 순으로 정렬할 수 있다.
    operations-sorter: method

    # swagger-ui default url인 petstore html의 비활성화 설정
    disable-swagger-default-url: true

    # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
    display-request-duration: true

  cache:
    disabled: true
  # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  #api-docs:
  #  path: /api-docs


  # request media type 의 기본 값
  #default-consumes-media-type: application/json

  # response media type 의 기본 값
  #default-produces-media-type: application/json

  # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
  #paths-to-match:
  #  - /api/**
swagger:
  host:
    domain: localhost:${server.port}
    protocol: http

---
spring:
  profiles:
    active: local